### ISSUE TITLE
Resource Pack Load lag

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [OsipXD/RPGInventory#1]
Is there anyway I can fix the lag from resource packs

**Comment by OsipXD** [comment]
To minimize lag you need set right hash and link to RP.

**Comment by xH3LLRAIZ3Rx** [comment]
I have done that

**Comment by OsipXD** [comment]
Impossible to completely remove lag

**Comment by xH3LLRAIZ3Rx** [comment]
its pretty big lag

**Comment by xH3LLRAIZ3Rx** [comment]
like freeze of game

**Comment by xH3LLRAIZ3Rx** [comment]
I will try with just the resource pack supplied

**Comment by OsipXD** [comment]
Ok

**Comment by xH3LLRAIZ3Rx** [comment]
yeah still lags really bad even with just your resource pack

**Comment by xH3LLRAIZ3Rx** [comment]
then again could it be because I have a mysql inventory saver that loads inventories on join?

**Comment by OsipXD** [comment]
I don't think it's because of this.
Try to disable may plugin and add RPGInv RP as server-resourcepack to server.properties and check lags.

**Comment by xH3LLRAIZ3Rx** [comment]
without rpginv and resource pack as server pack it doesnt lag

**Comment by OsipXD** [comment]
Stop. You use both RP? In plugin and in server.properties?

**Comment by xH3LLRAIZ3Rx** [comment]
yes, in the rpginv config and in server properties

**Comment by OsipXD** [comment]
You should combine resourcepacks into one zip and use only in plugin settings. I think, lags will be minimized

**Comment by xH3LLRAIZ3Rx** [comment]
oh.... I thought you had to put resource pack in server properties

**Comment by OsipXD** [comment]
Try and write me about results

**Comment by xH3LLRAIZ3Rx** [comment]
ok, first I will just try with resource pack that you supplied, since I have the info already in config

**Comment by OsipXD** [comment]
Ok

**Comment by xH3LLRAIZ3Rx** [comment]
reduced lag :D
