### ISSUE TITLE
Добавить поддержку классов и уровней моего плагина

### ISSUE THREAD

**Issue by nefallme** [OsipXD/RPGInventory#154]
я уже скинул вам вконтакте сам плагин
разработчик divineitemrpg добавил поддержку моего плагина
и выпускает обновы через спигот 
Сделайте так же как он ( что бы не попал мой плагин в чужие руки )

**Comment by Dereku** [comment]
Не вопрос - 50$ и поддержку самолично добавлю.

**Comment by osipxd** [comment]
Чтобы не слить плагин - придется сделать копии его интерфейсов, исходников нет, значит надо будет декомпилировать. Честно говоря добавлять это потом в основную ветку плагина нет особого смысла, лучшим вариантом было бы если вы найдёте программиста, который согласится сделать форк и обновлять его.
Или есть вариант дождаться [MimicAPI](https://github.com/EndlessCodeGroup/MimicAPI)
