### ISSUE TITLE
Players get double attributes

### ISSUE THREAD

**Issue by AaronHzy** [OsipXD/RPGInventory#159]
RPG Inventory Premium 2.1.6
DivineItemsRPG 3.2.5
PaperSpigot-1.12.2-b1409

When I put the weapon to the weapon slot
Players have 11 damage
When switching to the hand,Players have 22 damage

**Comment by osipxd** [comment]
Please follow bug report template: https://github.com/EndlessCodeGroup/RPGInventory/issues/new?template=Bug_report.md
