### ISSUE TITLE
Items dissapear

### ISSUE THREAD

**Issue by XXX10Tacles** [OsipXD/RPGInventory#164]
it never working with Worldguard's keep-inventory and sometimes it has problems with essentials keepinventory permission too.

**Comment by XXX10Tacles** [comment]
i dont recive any errors in coonsole

**Comment by osipxd** [comment]
Hello! Why have you closed the issue? Is it resolved?

**Comment by XXX10Tacles** [comment]
> Hello! Why have you closed the issue? Is it resolved?

yes kinda, it has own permissions for keeping inventory which i am using right now and working fine so far. would be nice to have worldguard flag for it in future tho.

**Comment by XXX10Tacles** [comment]
ow and hi sorry for my rudeness.
