### ISSUE TITLE
Add Hook MMOCore & QuantumRPG

### ISSUE THREAD

**Issue by Tylwen** [OsipXD/RPGInventory#165]
Hello,

I am writing to you to know if it is possible to add a hook for MMOCore & QuantumRPG plugins
For levels, classes & items

Sincerely

**Comment by osipxd** [comment]
Thank you for your report. I'll check if it is possible.

**Comment by Tylwen** [comment]
& MMOItems also

**Comment by osipxd** [comment]
Can you describe what integrations needed for each of the plugins?
MMOItems provides only items?
What we should integrate with QuantumRPG and MMOCore?

**Comment by osipxd** [comment]
Fixed in #170
