### ISSUE TITLE
Crash of new assemblies of mmoitems due to the update

### ISSUE THREAD

**Issue by VacAge** [OsipXD/RPGInventory#166]
After the last update of `MMOItems-6.5.1-SNAPSHOT`, `MMOLib-1.7.4`, `MMOCore-1.6.2` stopped working correctly a number of plugins interacting with `RPGInventory`, we with `MM` have already figured out that the plugins are crashing due to `RPGInventory`, therefore, I am writing to you with an error log... Most likely errors are caused in changing the API plugin `MMOItems` inventory.
Links to crash logs:
`https://pastebin.com/PUjUtZi8`
`https://pastebin.com/cA5Hv2qC`
`https://pastebin.com/V87xCzmn`

**Comment by osipxd** [comment]
Why do you think these crashes related to RPGInv?
I don't see any RPGInvetory classes in the logs, you've provided. As I know MMOItems integrates with RPGInv on their side.

**Comment by VacAge** [comment]
I already addressed support for mythicmobs team. How did I tell me the MMOITEMS developers (it's all because of rpginventory mesing up mmoitems which then messed up mireplacer) If you want to. I can make an absolutely clean server and once again test only two plugins MMOitems and RPGinventory and report if something changes...

**Comment by VacAge** [comment]
If you want to.  I can make an absolutely clean server and once again test only two plugins MMOitems and RPGinventory and report if something changes...

**Comment by osipxd** [comment]
It would be great to check these crashes with and without RPGInv

**Comment by VacAge** [comment]
I will check by 12:00 and write back with a court response.  Only with plugin MMOitems MMOCore MMOlib and RPGinv latest dev versions

**Comment by VacAge** [comment]
I found the problem, it was necessary to update ProtocolLib to version 486 from December 27th.

**Comment by VacAge** [comment]
Oh what ?! the error came back again as soon as I rebooted to the server for the second time ...
![image](https://user-images.githubusercontent.com/55461273/103341967-54515480-4a99-11eb-8ad9-6ebd41dcfb9e.png)
![image](https://user-images.githubusercontent.com/55461273/103341979-603d1680-4a99-11eb-8afa-fe4f9b5b6cbc.png)

**Comment by VacAge** [comment]
https://pastebin.com/d7FVrJgk Everything works on an empty server without other plugins and settings.
Perhaps this is a mistake in some settings? I just haven't edited anything lately, I just **updated** the plugins.

**Comment by osipxd** [comment]
It looks like you use [`RPGInventory-MMOItems Integration`](https://www.spigotmc.org/resources/75057/). Starting from MMOItems 5.3.2 it has built-in integration with RPGInv. So you don't need this addon.
I think MMOItems update broke this addon

**Comment by VacAge** [comment]
Yes thank you! Indeed, removing this plugin helped)
