### ISSUE TITLE
setDsn error

### ISSUE THREAD

**Issue by ZeTioZ** [OsipXD/RPGInventory#171]
Hi, I tried to compile and run the dev version of the plugin but it seems that there is something wrong with the dsn of the plugin tracker. here is the error.
[tmp.txt](https://github.com/EndlessCodeGroup/RPGInventory/files/5984992/tmp.txt)

**Comment by osipxd** [comment]
Thank you for your report!
I've added the commit (fc89fb0c12f4fa64b5b6cd9cf5b191b055b3384c) to fix this problem. Now you should be able to build RPGInv

**Comment by ZeTioZ** [comment]
> Thank you for your report!
> I've added the commit ([fc89fb0](https://github.com/EndlessCodeGroup/RPGInventory/commit/fc89fb0c12f4fa64b5b6cd9cf5b191b055b3384c)) to fix this problem. Now you should be able to build RPGInv

Thanks for the quick answer. However, it seems to not be fixed yet, I have an other error message ^^'
https://paste.gg/p/anonymous/1f3a8fbbe17d45799b3c985a3f7a88fa

**Comment by osipxd** [comment]
Try to place this string `"https://3ad55d59f82f48039fbb37e50f09de2d@o209384.ingest.sentry.io/1331962"` to `dsn` variable instead of `"no_dsn"`. If it works, I'll change hardcoded dsn.
https://github.com/EndlessCodeGroup/RPGInventory/blob/fc89fb0c12f4fa64b5b6cd9cf5b191b055b3384c/src/main/java/ru/endlesscode/rpginventory/RPGInventoryPlugin.java#L49

**Comment by ZeTioZ** [comment]
> Try to place this string `"https://3ad55d59f82f48039fbb37e50f09de2d@o209384.ingest.sentry.io/1331962"` to `dsn` variable instead of `"no_dsn"`. If it works, I'll change hardcoded dsn.
> https://github.com/EndlessCodeGroup/RPGInventory/blob/fc89fb0c12f4fa64b5b6cd9cf5b191b055b3384c/src/main/java/ru/endlesscode/rpginventory/RPGInventoryPlugin.java#L49

Well, it seems to not have this error anymore but it has some dependencies issues I guess. I use the "all" jar with all the libs shaded in but I still have a CNFE error.
https://paste.md-5.net/pujiyupifu.bash

**Comment by osipxd** [comment]
Look like you've not installed [Mimic](https://www.spigotmc.org/resources/82515/) plugin

**Comment by ZeTioZ** [comment]
> Look like you've not installed [Mimic](https://www.spigotmc.org/resources/82515/) plugin

Yup, I installed it and all's good.

**Comment by osipxd** [comment]
I want to keep this issue to not forget to fix these issues.

**Comment by osipxd** [comment]
Fixed in fc89fb0c12f4fa64b5b6cd9cf5b191b055b3384c

**Comment by osipxd** [comment]
Verified it was fixed in 2.4.0
