### ISSUE TITLE
Duplication bug in 2.4.0 version

### ISSUE THREAD

**Issue by armandkoltai** [OsipXD/RPGInventory#176]
To reproduce:

Just open anything like a crate preview, or a dtltraders shop, and press F while hovering an item with your cursor. Its that simple.

Also, it would be great if the shield slot configuring could be fully optional. Its really annoying that you cant just take any item in your left hand, you have to add all the id's one by one in the slots.yml.

**Comment by osipxd** [comment]
1. It is not really a dupe, because item disappears when player tries to take it out of offhand slot. But I'll fix it in the next version
2. It is already fully optional. You can just remove SHIELD slot from config.
