### ISSUE TITLE
RPG Inventory slots not completly showing

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [OsipXD/RPGInventory#2]
The slots in the GUI only show a couple items, the rest is not there.

Not only that but also all placeholder variables do not work

**Comment by OsipXD** [comment]
You use new resource pack?

**Comment by xH3LLRAIZ3Rx** [comment]
well I combined it with the BitBetter resource pack

**Comment by OsipXD** [comment]
Problem resolved?

**Comment by xH3LLRAIZ3Rx** [comment]
nope

**Comment by OsipXD** [comment]
Can you provide me screenshot of problem&

**Comment by xH3LLRAIZ3Rx** [comment]
well I cant because I uninstalled it, but the problem is I think it never replaced hoe

**Comment by xH3LLRAIZ3Rx** [comment]
but armor slots show

**Comment by OsipXD** [comment]
What version of MC?

**Comment by xH3LLRAIZ3Rx** [comment]
1.11

**Comment by OsipXD** [comment]
What resourcepack you used? (link)

**Comment by xH3LLRAIZ3Rx** [comment]
https://mods.curse.com/texture-packs/minecraft/223591-bitbetter-1-7-10-v1-2

**Comment by OsipXD** [comment]
No, I mean what RPGInv resource-pack you used?

**Comment by xH3LLRAIZ3Rx** [comment]
the one for 1.11, I combined that with BitBetter

**Comment by xH3LLRAIZ3Rx** [comment]
https://dl.dropboxusercontent.com/u/105899524/RPGInventory/RPs/Default_v3.zip

**Comment by OsipXD** [comment]
Hmmm... Without combining it works for you?

**Comment by xH3LLRAIZ3Rx** [comment]
have not tried yet, will give it a try soon

**Comment by OsipXD** [comment]
Ok

**Comment by xH3LLRAIZ3Rx** [comment]
just tried it, same issue, now with screenshot http://i.imgur.com/fmZDGqL.png

**Comment by OsipXD** [comment]
Oh. Can you disable custom RP?

**Comment by OsipXD** [comment]
Temporary

**Comment by xH3LLRAIZ3Rx** [comment]
in rpginv config or server properties?

**Comment by OsipXD** [comment]
I mean you 64x RP in your client. May be it conflicts with 16x RP of RPGInv

**Comment by xH3LLRAIZ3Rx** [comment]
maybe, I will try that, another note, I am using bungeecord

**Comment by OsipXD** [comment]
I do not think it's problem of bungeecord

**Comment by xH3LLRAIZ3Rx** [comment]
ok so I loaded resource pack via config and not server properties, and removed my client pack, having same issue, diamond hoe didnt change texture, and also this issue: http://i.imgur.com/UqtlR3v.png

**Comment by xH3LLRAIZ3Rx** [comment]
huh its just happening to me....

**Comment by xH3LLRAIZ3Rx** [comment]
I open others and its fine http://i.imgur.com/RpyqRlf.png

**Comment by xH3LLRAIZ3Rx** [comment]
the placeholder issue though is everyones issue

**Comment by xH3LLRAIZ3Rx** [comment]
do note, the inventory issue just fixed itself when re-logging

**Comment by xH3LLRAIZ3Rx** [comment]
one little issue, cannot take off armor in armor slots, need to go into rpginv to do so

**Comment by OsipXD** [comment]
Do you have installed PlaceholderAPI? If yes - use [these placeholders](https://www.spigotmc.org/resources/12498/update?update=121721).
About armor - it's not issue it's feature :D
