### ISSUE TITLE
Annoying health effect

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [OsipXD/RPGInventory#5]
When using RPGInventory I noticed that when you scroll in your hotbar your screen flashes as if you keep losing hearts, is this intended? if not can you fix it?

**Comment by OsipXD** [comment]
Can you record video?

**Comment by xH3LLRAIZ3Rx** [comment]
here you go https://media.giphy.com/media/wZuapu7yhcxyg/giphy.gif

**Comment by OsipXD** [comment]
So strange. It's only in creative mode, or in survival too?

**Comment by xH3LLRAIZ3Rx** [comment]
both

**Comment by OsipXD** [comment]
You've tested it on clear server with only RPGInventory, ProtocolLib, Lib's Disguisses and Vault?

**Comment by xH3LLRAIZ3Rx** [comment]
Not yet, will do though, could it be my custom enchant plugins? I have these:

- RunesEnchant [Link](https://www.spigotmc.org/resources/runesenchant-recoded-beta.19363)
- Zenchantments [Link](https://dev.bukkit.org/projects/zenchantments)
- EmeraldEnchants [Link](https://dev.bukkit.org/projects/emerald-enchants)

**Comment by OsipXD** [comment]
I've not tested my plugin with these all

**Comment by xH3LLRAIZ3Rx** [comment]
found out it was a different plugin

**Comment by OsipXD** [comment]
Write here what plugin.

**Comment by xH3LLRAIZ3Rx** [comment]
I am actually not sure, but it could be Zenchantments, and it has nothing to do with RPGInventory compatibility
