### ISSUE TITLE
Hunger issue and Items disappearing from inventory

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [OsipXD/RPGInventory#6]
There is some type of issue with the hunger bar, not sure how to reproduce but it seems glitchy (one player told me so) 

Randomly players items disappear, not sure why, but its happening

**Comment by OsipXD** [comment]
Try to test it on clean client.

**Comment by xH3LLRAIZ3Rx** [comment]
could be a food plugin I have lol, not sure though, only 1 player said about it, so I guess I will just close the issue
